#!/usr/bin/env python3
"""Build data/alltime-players.json with real historical CFB players only."""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def cost_for_ovr(ovr: int) -> int:
    x = max(0, int(ovr) - 39)
    return int(round(8 + (x ** 2) * 0.22))

def make_id(slug: str, name: str) -> str:
    s = (
        name.lower()
        .replace(".", "")
        .replace("'", "")
        .replace("'", "")
        .replace(" ", "-")
        .replace(",", "")
    )
    return f"{slug}-{s}"

RAW: dict[str, tuple[str, str, list[tuple[str, str, int]]]] = {}

def T(tid: str, slug: str, school: str, players: list[tuple[str, str, int]]) -> None:
    best: dict[str, tuple[str, str, int]] = {}
    for n, p, o in players:
        if n not in best or o > best[n][2]:
            best[n] = (n, p, int(o))
    RAW[tid] = (slug, school, list(best.values()))

# ===================== SEC =====================
T("333","ala","Alabama",[
 ("Joe Namath","QB",96),("Ken Stabler","QB",90),("Bart Starr","QB",88),("AJ McCarron","QB",86),
 ("Tua Tagovailoa","QB",94),("Bryce Young","QB",95),("Jalen Hurts","QB",88),("Mac Jones","QB",87),
 ("Jay Barker","QB",82),("Harry Gilmer","QB",85),("Scott Hunter","QB",78),("Brodie Croyle","QB",80),
 ("Mark Ingram","RB",94),("Derrick Henry","RB",96),("Trent Richardson","RB",90),("Najee Harris","RB",91),
 ("Shaun Alexander","RB",89),("Bobby Humphrey","RB",85),("Johnny Musso","RB",86),("Brian Robinson Jr.","RB",84),
 ("Jalston Fowler","RB",78),("Bobby Marlow","RB",84),("Kerry Goode","RB",76),
 ("Julio Jones","WR",97),("Amari Cooper","WR",94),("Jerry Jeudy","WR",92),("Devonta Smith","WR",96),
 ("Jaylen Waddle","WR",93),("Calvin Ridley","WR",90),("Don Hutson","WR",98),("David Palmer","WR",84),
 ("DJ Hall","WR",82),("Ozzie Newsome","TE",93),("OJ Howard","TE",88),("Irv Smith","TE",84),
 ("Cameron Latu","TE",80),("Barrett Jones","OL",92),("Andre Smith","OL",91),("Jonah Williams","OL",88),
 ("Alex Leatherwood","OL",86),("Evan Neal","OL",90),("John Hannah","OL",97),("Dwight Stephenson","OL",95),
 ("Quinnen Williams","DL",94),("Derrick Thomas","LB",98),("Rolando McClain","LB",90),("C.J. Mosley","LB",93),
 ("Reuben Foster","LB",91),("Will Anderson Jr.","LB",96),("Dont'a Hightower","LB",92),("Cornelius Bennett","LB",94),
 ("Lee Roy Jordan","LB",92),("Woodrow Lowe","LB",88),("Mark Barron","DB",89),("Minkah Fitzpatrick","DB",95),
 ("Landauon Collins","DB",90),("Xavier McKinney","DB",87),("Kool-Aid McKinstry","DB",88),("Antonio Langham","DB",86),
 ("Leigh Tiffin","K",78),("JK Scott","P",82),("Van Tiffin","K",84),
])
T("61","uga","Georgia",[
 ("Herschel Walker","RB",99),("Todd Gurley","RB",95),("Nick Chubb","RB",96),("Sony Michel","RB",90),
 ("Knowshon Moreno","RB",88),("D'Andre Swift","RB",89),("Garrison Hearst","RB",90),("Lars Tate","RB",82),
 ("Matthew Stafford","QB",94),("Aaron Murray","QB",87),("Jake Fromm","QB",85),("Stetson Bennett","QB",90),
 ("David Greene","QB",84),("Fran Tarkenton","QB",92),("Eric Zeier","QB",83),("Buck Belue","QB",80),
 ("AJ Green","WR",96),("Hines Ward","WR",88),("George Pickens","WR",88),("Ladd McConkey","WR",87),
 ("Malcolm Mitchell","WR",84),("Terrence Edwards","WR",83),("Fred Gibson","WR",80),("Mohamed Sanu","WR",82),
 ("Brock Bowers","TE",97),("Ben Watson","TE",86),("Darnell Washington","TE",86),("Leonard Pope","TE",80),
 ("Bill Stanfill","DL",92),("Richard Seymour","DL",94),("Jordan Davis","DL",93),("Jalen Carter","DL",95),
 ("David Pollack","DL",94),("Roquan Smith","LB",96),("Nakobe Dean","LB",92),("Jarvis Jones","LB",88),
 ("Boss Bailey","LB",85),("Champ Bailey","DB",97),("Deandre Baker","DB",86),("Lewis Cine","DB",85),
 ("Kelee Ringo","DB",84),("Jake Camarda","P",83),("Rodrigo Blankenship","K",86),("Matt Stinchcomb","OL",90),
])
T("251","tex","Texas",[
 ("Vince Young","QB",96),("Colt McCoy","QB",90),("Sam Ehlinger","QB",84),("Quinn Ewers","QB",86),
 ("Bobby Layne","QB",91),("James Street","QB",84),("Major Applewhite","QB",82),("Chris Simms","QB",80),
 ("Ricky Williams","RB",98),("Earl Campbell","RB",99),("Cedric Benson","RB",90),("Jamaal Charles","RB",93),
 ("Bijan Robinson","RB",95),("Roschon Johnson","RB",84),("Priest Holmes","RB",86),("Eric Metcalf","RB",88),
 ("Roy Williams","WR",94),("Jordan Shipley","WR",86),("Xavier Worthy","WR",90),("Michael Pittman Jr.","WR",87),
 ("Quan Cosby","WR",82),("Jermichael Finley","TE",88),("Ja'Tavion Sanders","TE",86),("Cade Stover","TE",84),
 ("Kenneth Sims","DL",92),("Steve McMichael","DL",90),("Casey Hampton","DL",87),("Brian Orakpo","LB",90),
 ("Derrick Johnson","LB",93),("Tommy Nobis","LB",96),("Doug English","DL",88),("Michael Huff","DB",88),
 ("Aaron Ross","DB",86),("Earl Thomas","DB",95),("Quandre Diggs","DB",85),("Nathan Vasher","DB",84),
 ("Justin Tucker","K",92),("Michael Dickson","P",90),
])
T("99","lsu","LSU",[
 ("Joe Burrow","QB",99),("Jayden Daniels","QB",94),("JaMarcus Russell","QB",86),("Tommy Hodson","QB",84),
 ("Bert Jones","QB",88),("Matt Mauck","QB",82),("Zach Mettenberger","QB",81),("Rohan Davey","QB",80),
 ("Leonard Fournette","RB",95),("Kevin Faulk","RB",90),("Billy Cannon","RB",97),("Charles Scott","RB",84),
 ("Jeremy Hill","RB",86),("Jacob Hester","RB",82),("Odell Beckham Jr.","WR",95),("Jarvis Landry","WR",90),
 ("Justin Jefferson","WR",97),("Ja'Marr Chase","WR",96),("Josh Reed","WR",88),("Dwayne Bowe","WR",87),
 ("Michael Clayton","WR",86),("Foster Moreau","TE",82),("Glenn Dorsey","DL",94),("Marcus Spears","DL",88),
 ("Tyson Jackson","DL",84),("Barkevious Mingo","LB",86),("Devin White","LB",92),("Patrick Queen","LB",88),
 ("Tyrann Mathieu","DB",96),("Patrick Peterson","DB",95),("Morris Claiborne","DB",90),("Derek Stingley Jr.","DB",93),
 ("Grant Delpit","DB",88),("LaRon Landry","DB",89),("Corey Webster","DB",85),("Jerry Stovall","DB",86),
])
T("2","aub","Auburn",[
 ("Cam Newton","QB",97),("Pat Sullivan","QB",92),("Jason Campbell","QB",84),("Nick Marshall","QB",82),
 ("Bo Jackson","RB",99),("Cadillac Williams","RB",90),("Tre Mason","RB",88),("Kerryon Johnson","RB",86),
 ("Ronnie Brown","RB",89),("James Brooks","RB",86),("Stephen Davis","RB",85),("Tucker Frederickson","RB",84),
 ("Sammy Watkins","WR",93),("Frank Sanders","WR",86),("Ben Obomanu","WR",80),("Philip Lutzenkirchen","TE",78),
 ("Nick Fairley","DL",92),("Tracy Rocker","DL",90),("Derrick Brown","DL",91),("Carl Lawson","DL",86),
 ("Takeo Spikes","LB",90),("Karlos Dansby","LB",88),("Carlos Rogers","DB",88),("Daniel Carlson","K",88),
 ("Greg Robinson","OL",88),("Kendall Simmons","OL",84),
])
T("57","fla","Florida",[
 ("Tim Tebow","QB",95),("Danny Wuerffel","QB",93),("Steve Spurrier","QB",90),("Rex Grossman","QB",86),
 ("Chris Leak","QB",84),("Kyle Trask","QB",88),("Emmitt Smith","RB",97),("Fred Taylor","RB",90),
 ("Errict Rhett","RB",88),("Percy Harvin","WR",93),("Ike Hilliard","WR",88),("Kadarius Toney","WR",88),
 ("Ricky Nattiel","WR",84),("Wes Chandler","WR",90),("Cris Collinsworth","WR",88),("Carlos Alvarez","WR",86),
 ("Aaron Hernandez","TE",90),("Kyle Pitts","TE",94),("Alex Brown","DL",88),("Jack Youngblood","DL",94),
 ("Jevon Kearse","LB",94),("Brandon Spikes","LB",90),("Wilber Marshall","LB",93),("Joe Haden","DB",92),
 ("Janoris Jenkins","DB",88),("Vernon Hargreaves","DB",87),("Keanu Neal","DB",84),("Lomas Brown","OL",90),
 ("Maurkice Pouncey","OL",88),("Mike Pouncey","OL",86),("Jeff Chandler","K",80),
])
T("201","ou","Oklahoma",[
 ("Baker Mayfield","QB",95),("Kyler Murray","QB",94),("Jason White","QB",93),("Sam Bradford","QB",94),
 ("Josh Heupel","QB",88),("Jack Mildren","QB",84),("Adrian Peterson","RB",97),("Billy Sims","RB",96),
 ("Steve Owens","RB",93),("Joe Washington","RB",90),("DeMarco Murray","RB",90),("Samaje Perine","RB",86),
 ("Greg Pruitt","RB",90),("CeeDee Lamb","WR",95),("Marquise Brown","WR",90),("Ryan Broyles","WR",88),
 ("Mark Clayton","WR",90),("Sterling Shepard","WR",86),("Dede Westbrook","WR",88),("Keith Jackson","TE",94),
 ("Jermaine Gresham","TE",86),("Lee Roy Selmon","DL",97),("Tommie Harris","DL",90),("Gerald McCoy","DL",92),
 ("Brian Bosworth","LB",94),("Rocky Calmus","LB",88),("Teddy Lehman","LB",88),("Roy Williams","DB",94),
 ("Tony Jefferson","DB",84),("Tress Way","P",86),("Uwe von Schamann","K",82),
])
T("145","miss","Ole Miss",[
 ("Eli Manning","QB",92),("Archie Manning","QB",93),("Matt Corral","QB",86),("Chad Kelly","QB",84),
 ("Deuce McAllister","RB",92),("Dexter McCluster","RB",86),("Quinshon Judkins","RB",88),
 ("AJ Brown","WR",94),("DK Metcalf","WR",93),("Laquon Treadwell","WR",88),("Donte Moncrief","WR",86),
 ("Jonathan Mingo","WR",84),("Evan Engram","TE",90),("Patrick Willis","LB",96),("Robert Nkemdiche","DL",88),
 ("Senquez Golson","DB",84),
])
T("2633","tenn","Tennessee",[
 ("Peyton Manning","QB",99),("Tee Martin","QB",84),("Hendon Hooker","QB",88),("Condredge Holloway","QB",86),
 ("Casey Clausen","QB",80),("Jamal Lewis","RB",92),("Travis Henry","RB",88),("Alvin Kamara","RB",90),
 ("Arian Foster","RB",86),("Johnny Majors","RB",88),("Peerless Price","WR",88),("Jalin Hyatt","WR",90),
 ("Stanley Morgan","WR",88),("Jason Witten","TE",94),("Reggie White","DL",98),("Doug Atkins","DL",95),
 ("John Henderson","DL",90),("Leonard Little","DL",88),("Jerod Mayo","LB",90),("Al Wilson","LB",92),
 ("Eric Berry","DB",95),("Antoine Winfield","DB",90),("Deon Grant","DB",84),("Dustin Colquitt","P",86),
])
T("8","ark","Arkansas",[
 ("Ryan Mallett","QB",86),("Joe Ferguson","QB",84),("Matt Jones","QB",82),("Darren McFadden","RB",95),
 ("Felix Jones","RB",88),("Madre Hill","RB",82),("Lance Alworth","WR",96),("Cobi Hamilton","WR",84),
 ("Jarius Wright","WR",82),("Hunter Henry","TE",90),("Steve Atwater","DB",94),("Dan Hampton","DL",92),
 ("Billy Ray Smith","LB",88),("Kenoy Kennedy","DB",82),
])
T("245","tam","Texas A&M",[
 ("Johnny Manziel","QB",95),("Ryan Tannehill","QB",88),("Kellen Mond","QB",82),("Bucky Richardson","QB",80),
 ("John David Crow","RB",93),("Darren Lewis","RB",84),("Cyrus Gray","RB",82),("Mike Evans","WR",95),
 ("Christian Kirk","WR",88),("Martellus Bennett","TE",88),("Myles Garrett","DL",97),("Von Miller","LB",96),
 ("Dat Nguyen","LB",92),("Johnny Holland","LB",86),("Shane Lechler","P",94),("Luke Joeckel","OL",90),
 ("Jake Matthews","OL",88),
])
T("142","miz","Missouri",[
 ("Chase Daniel","QB",86),("Blaine Gabbert","QB",84),("Drew Lock","QB",86),("Brad Smith","QB",88),
 ("Jeremy Maclin","WR",90),("Danario Alexander","WR",86),("Justin Smith","DL",92),("Aldon Smith","LB",90),
 ("Sean Weatherspoon","LB",86),("William Moore","DB",84),("Henry Josey","RB",82),("Harrison Mevis","K",86),
])
T("2579","scar","South Carolina",[
 ("George Rogers","RB",95),("Marcus Lattimore","RB",90),("Connor Shaw","QB",84),("Jadeveon Clowney","DL",97),
 ("Melvin Ingram","DL",90),("Alshon Jeffery","WR",92),("Sidney Rice","WR",86),("Sterling Sharpe","WR",94),
 ("Hayden Hurst","TE",86),("John Abraham","DL",88),("Pharoh Cooper","WR",84),("Ryan Succop","K",84),
])
T("96","uk","Kentucky",[
 ("Tim Couch","QB",90),("George Blanda","QB",88),("Babe Parilli","QB",86),("Lynn Bowden","WR",86),
 ("Benny Snell","RB",88),("Randall Cobb","WR",90),("Josh Allen","LB",94),("Bud Dupree","LB",88),
 ("Art Still","DL",90),("Dermontti Dawson","OL",92),("Za'Darius Smith","DL",86),
])
T("344","msst","Mississippi State",[
 ("Dak Prescott","QB",94),("Nick Fitzgerald","QB",82),("Anthony Dixon","RB",84),("Vick Ballard","RB",82),
 ("Fred Smoot","DB",86),("K.J. Wright","LB",88),("Fletcher Cox","DL",92),("Johnthan Banks","DB",86),
 ("Chris Jones","DL",90),("Gabe Jackson","OL",86),
])
T("238","van","Vanderbilt",[
 ("Jay Cutler","QB",90),("Bill Wade","QB",86),("Earl Bennett","WR",86),("Jordan Matthews","WR",88),
 ("Zach Cunningham","LB",90),("Casey Hayward","DB",88),("Ralph Webb","RB",80),("Ke'Shawn Vaughn","RB",84),
])

# ===================== Big Ten =====================
T("194","osu","Ohio State",[
 ("Archie Griffin","RB",98),("Eddie George","RB",95),("Ezekiel Elliott","RB",94),("Chris Wells","RB",90),
 ("Maurice Clarett","RB",86),("Carlos Hyde","RB",86),("J.T. Barrett","QB",86),("Troy Smith","QB",94),
 ("Cardale Jones","QB",84),("Justin Fields","QB",92),("C.J. Stroud","QB",95),("Art Schlichter","QB",84),
 ("Rex Kern","QB",88),("Cris Carter","WR",94),("Terry Glenn","WR",90),("Michael Jenkins","WR",86),
 ("Ted Ginn Jr.","WR",88),("Santonio Holmes","WR",88),("David Boston","WR",88),("Chris Olave","WR",90),
 ("Garrett Wilson","WR",92),("Marvin Harrison Jr.","WR",95),("Nick Bosa","DL",97),("Joey Bosa","DL",96),
 ("Chase Young","DL",95),("Mike Vrabel","LB",90),("A.J. Hawk","LB",92),("James Laurinaitis","LB",92),
 ("Chris Spielman","LB",94),("Randy Gradishar","LB",93),("Malcolm Jenkins","DB",90),("Antoine Winfield Jr.","DB",88),
 ("Shawn Springs","DB",88),("Orlando Pace","OL",97),("LeCharles Bentley","OL",88),("Billy Price","OL",86),
 ("Mike Nugent","K",84),("Jack Tatum","DB",95),("Jim Parker","OL",96),
])
T("130","mich","Michigan",[
 ("Tom Brady","QB",92),("Jim Harbaugh","QB",88),("Elvis Grbac","QB",84),("Chad Henne","QB",84),
 ("Denard Robinson","QB",88),("J.J. McCarthy","QB",90),("Desmond Howard","WR",95),("Braylon Edwards","WR",92),
 ("Anthony Carter","WR",93),("Mario Manningham","WR",86),("Charles Woodson","DB",98),("Ty Law","DB",90),
 ("Jourdan Lewis","DB",86),("Donovan Edwards","RB",86),("Blake Corum","RB",90),("Chris Perry","RB",88),
 ("Mike Hart","RB",90),("Jamie Morris","RB",84),("Ron Kramer","TE",90),("Jake Butt","TE",86),
 ("Aidan Hutchinson","DL",96),("LaMarr Woodley","LB",92),("Erick Anderson","LB",86),("Tripp Welborne","DB",88),
 ("Jake Long","OL",94),("Steve Hutchinson","OL",95),("Zoltan Mesko","P",86),("Tom Harmon","RB",96),
 ("Bennie Oosterbaan","WR",90),("Dan Dierdorf","OL",92),
])
T("213","psu","Penn State",[
 ("John Cappelletti","RB",94),("Ki-Jana Carter","RB",90),("Larry Johnson","RB",92),("Saquon Barkley","RB",96),
 ("Curtis Enis","RB",88),("Kerry Collins","QB",90),("Michael Robinson","QB",84),("Trace McSorley","QB",86),
 ("Sean Clifford","QB",82),("Bobby Engram","WR",88),("Allen Robinson","WR",90),("Chris Godwin","WR",88),
 ("Mike Gesicki","TE",88),("Kyle Brady","TE",86),("Courtney Brown","DL",90),("Tamba Hali","DL",90),
 ("LaVar Arrington","LB",95),("Paul Posluszny","LB",92),("NaVorro Bowman","LB",93),("Sean Lee","LB",88),
 ("Shane Conlan","LB",90),("Lenny Moore","RB",95),("Jack Ham","LB",96),("Franco Harris","RB",92),
 ("Mike Reid","DL",90),("Robbie Gould","K",84),
])
T("2483","ore","Oregon",[
 ("Marcus Mariota","QB",95),("Joey Harrington","QB",88),("Justin Herbert","QB",94),("Dennis Dixon","QB",86),
 ("LaMichael James","RB",90),("Jonathan Stewart","RB",90),("Kenjon Barner","RB",84),("Royce Freeman","RB",86),
 ("De'Anthony Thomas","WR",86),("Josh Huff","WR",84),("Haloti Ngata","DL",94),("DeForest Buckner","DL",92),
 ("Kayvon Thibodeaux","LB",90),("Ahmad Rashad","WR",90),("Mel Renfro","DB",94),("Norm Van Brocklin","QB",92),
 ("Dan Fouts","QB",90),
])
T("30","usc","USC",[
 ("Carson Palmer","QB",94),("Matt Leinart","QB",93),("Matt Barkley","QB",84),("Sam Darnold","QB",88),
 ("Caleb Williams","QB",96),("Cody Kessler","QB",82),("Reggie Bush","RB",96),("Marcus Allen","RB",98),
 ("O.J. Simpson","RB",99),("Charles White","RB",95),("Mike Garrett","RB",93),("LenDale White","RB",88),
 ("Keyshawn Johnson","WR",92),("Marqise Lee","WR",90),("Robert Woods","WR",88),("Dwayne Jarrett","WR",86),
 ("Mike Williams","WR",88),("Jordan Addison","WR",90),("Junior Seau","LB",97),("Rey Maualuga","LB",88),
 ("Clay Matthews","LB",90),("Ronnie Lott","DB",97),("Dennis Smith","DB",88),("Mark Carrier","DB",86),
 ("Adoree' Jackson","DB",88),("Anthony Davis","OL",90),("Tony Boselli","OL",94),("Bruce Matthews","OL",95),
])
T("26","ucla","UCLA",[
 ("Troy Aikman","QB",94),("Cade McNown","QB",86),("Brett Hundley","QB",84),("Dorian Thompson-Robinson","QB",82),
 ("Freeman McNeil","RB",90),("Gaston Green","RB",86),("Paul Perkins","RB",82),("Kenny Washington","RB",92),
 ("Skip Hicks","RB",84),("J.J. Stokes","WR",90),("Freddie Mitchell","WR",84),("Caleb Wilson","TE",84),
 ("Jonathan Ogden","OL",96),("Kenny Easley","DB",95),("Eric Kendricks","LB",90),("Myles Jack","LB",88),
 ("Ka'imi Fairbairn","K",86),
])
T("264","wash","Washington",[
 ("Warren Moon","QB",90),("Marques Tuiasosopo","QB",84),("Jake Locker","QB",86),("Cody Pickett","QB",80),
 ("Napoleon Kaufman","RB",90),("Corey Dillon","RB",92),("Bishop Sankey","RB",84),("Myles Gaskin","RB",86),
 ("Mario Bailey","WR",86),("Jermaine Kearse","WR",84),("Reggie Williams","WR",86),("Dante Pettis","WR",84),
 ("Steve Emtman","DL",96),("Lawyer Milloy","DB",90),("Budda Baker","DB",92),("Marcus Trufant","DB",86),
])
T("84","iu","Indiana",[
 ("Antwaan Randle El","QB",88),("Nate Sudfeld","QB",80),("Tre Roberson","QB",78),("Levron Williams","RB",84),
 ("Anthony Thompson","RB",90),("Vaughn Dunbar","RB",86),("Ernie Pannell","WR",74),("Tandon Doss","WR",80),
 ("Ted Kluszewski","OL",70),("Tegray Scales","LB",84),("Eric Moore","OL",82),
])
T("2294","iowa","Iowa",[
 # Ferentz-era / notable QBs (starters ~2000–present) + program legends
 ("Chuck Long","QB",90),("Brad Banks","QB",86),("Drew Tate","QB",84),("Ricky Stanzi","QB",84),
 ("C.J. Beathard","QB",83),("Nate Stanley","QB",80),("James Vandenberg","QB",76),
 ("Nathan Chandler","QB",75),("Kyle McCann","QB",74),("Spencer Petras","QB",70),
 # RBs — post-2000 standouts + legends already catalogued
 ("Nile Kinnick","RB",95),("Shonn Greene","RB",92),("Ladell Betts","RB",88),("Tavian Banks","RB",88),
 ("Kaleb Johnson","RB",88),("Albert Young","RB",86),("Akrum Wadley","RB",84),("Fred Russell","RB",84),
 ("Marcus Coker","RB",82),("Sedrick Shaw","RB",82),("Mark Weisman","RB",78),
 # WRs
 ("Tim Dwight","WR",88),("Marvin McNutt","WR",86),("Kevin Kasper","WR",84),
 ("Derrell Johnson-Koulianos","WR",82),("Kevonte Martin-Manley","WR",82),("Kahlil Hill","WR",82),
 ("Clinton Solomon","WR",80),("Ihmir Smith-Marsette","WR",80),
 # TEs (Tight End U)
 ("Dallas Clark","TE",92),("T.J. Hockenson","TE",90),("Sam LaPorta","TE",90),("Noah Fant","TE",88),
 ("George Kittle","TE",86),("Scott Chandler","TE",84),("C.J. Fiedorowicz","TE",82),("Tony Moeaki","TE",82),
 # Elite OL only (All-Big Ten / NFL draft caliber)
 ("Brandon Scherff","OL",94),("Tristan Wirfs","OL",93),("Robert Gallery","OL",90),("Tyler Linderbaum","OL",92),
 ("Eric Steinbach","OL",90),("Marshal Yanda","OL",88),("Bryan Bulaga","OL",88),("Riley Reiff","OL",86),
 ("James Daniels","OL",86),("Austin Blythe","OL",84),
 # Existing defense / ST kept
 ("Andre Tippett","LB",94),("Chad Greenway","LB",90),("Josey Jewell","LB",88),("Nate Kaeding","K",88),
])
T("275","wis","Wisconsin",[
 ("Ron Dayne","RB",96),("Montee Ball","RB",92),("Jonathan Taylor","RB",95),("Melvin Gordon","RB",93),
 ("Brent Moss","RB",86),("Russell Wilson","QB",94),("Darrell Bevell","QB",82),("Jim Leonhard","DB",88),
 ("J.J. Watt","DL",90),("Chris McIntosh","OL",88),("Joe Thomas","OL",96),("Travis Beckum","TE",84),
 ("Lee Evans","WR",90),("Jared Abbrederis","WR",84),("Michael Bennett","DL",86),("Chris Chambers","WR",86),
])
T("158","neb","Nebraska",[
 ("Tommie Frazier","QB",95),("Eric Crouch","QB",90),("Scott Frost","QB",86),("Turner Gill","QB",88),
 ("Ahman Green","RB",92),("Mike Rozier","RB",96),("Roger Craig","RB",90),("Rex Burkhead","RB",84),
 ("Johnny Rodgers","WR",96),("Irving Fryar","WR",92),("Kenny Bell","WR",84),("Ndamukong Suh","DL",97),
 ("Grant Wistrom","DL",90),("Trev Alberts","LB",92),("Barrett Ruud","LB",86),("Mike Brown","DB",88),
 ("Dave Rimington","OL",95),("Will Shields","OL",94),("Eric Crouch","QB",90),
])
T("135","minn","Minnesota",[
 ("Marion Barber III","RB",88),("Laurence Maroney","RB",86),("Darrell Thompson","RB",84),("Adam Weber","QB",78),
 ("Marlenece Williams","WR",74),("Eric Decker","WR",86),("Ra'Shede Hageman","DL",88),("Tyrone Carter","DB",84),
 ("Bruce Smith","RB",97),("Bobby Bell","LB",94),("Sandy Stephens","QB",86),
])
T("127","msu","Michigan State",[
 ("Connor Cook","QB",84),("Kirk Cousins","QB",88),("Drew Stanton","QB",82),("Lorenzo White","RB",92),
 ("Le'Veon Bell","RB",94),("Javon Ringer","RB",86),("Plaxico Burress","WR",92),("Charles Rogers","WR",90),
 ("Todd Schultz","TE",74),("Bubba Smith","DL",94),("Julian Peterson","LB",90),("Greg Jones","LB",86),
 ("Darqueze Dennard","DB",88),("T.J. Duckett","RB",86),("Morty Mulligan","QB",70),
])
T("356","ill","Illinois",[
 ("Jeff George","QB",88),("Juice Williams","QB",80),("Nathan Scheelhaase","QB",80),("Red Grange","RB",98),
 ("Rashard Mendenhall","RB",88),("Mikel Leshoure","RB",84),("Brandon Lloyd","WR",86),("Whitney Mercilus","LB",90),
 ("Simeon Rice","DL",94),("Dana Howard","LB",86),("Kevin Hardy","LB",88),
])
T("120","md","Maryland",[
 ("Boomer Esiason","QB",90),("Scott Milanovich","QB",78),("LaMont Jordan","RB",88),("Charlie Wysocki","RB",82),
 ("Vernon Davis","TE",92),("Darrius Heyward-Bey","WR",84),("Torrey Smith","WR",88),("Shawne Merriman","LB",90),
 ("E.J. Henderson","LB",88),("Randy White","DL",95),("Frank Reich","QB",82),
])
T("2509","pur","Purdue",[
 ("Drew Brees","QB",96),("Bob Griese","QB",94),("Jim Everett","QB",88),("Kyle Orton","QB",82),
 ("Mike Alstott","RB",90),("Otsego Otsego","RB",70),("Taylor Stubblefield","WR",84),("John Standeford","WR",80),
 ("Matt Light","OL",88),("Ryan Kerrigan","LB",90),("Rod Woodson","DB",95),("Mark Herrmann","QB",86),
])
# Drop nonsense name
RAW["2509"]=("pur","Purdue",[(n,p,o) for n,p,o in RAW["2509"][2] if n!="Otsego Otsego"])
T("77","nu","Northwestern",[
 ("Brett Basanez","QB",80),("Dan Persa","QB",82),("Clayton Thorson","QB",78),("Justin Jackson","RB",86),
 ("Darnell Autry","RB",84),("Venric Mark","RB",80),("Rashied Davis","WR",78),("Drake Dunsmore","TE",80),
 ("Pat Fitzgerald","LB",88),("Napoleon Harris","LB",86),("Luke Johnsos","WR",74),
])
T("164","rutg","Rutgers",[
 ("Ray Rice","RB",92),("Brian Leonard","RB",84),("Mohamed Sanu","WR",86),("Kenny Britt","WR",88),
 ("Mike Teel","QB",78),("Eric LeGrand","DL",82),("Devin McCourty","DB",90),("Jason McCourty","DB",86),
])


MORE_TEAMS = {'103': ('bc',
         'Boston College',
         [('Matt Ryan', 'QB', 94),
          ('Doug Flutie', 'QB', 95),
          ('Luke Kuechly', 'LB', 97),
          ('Montel Harris', 'RB', 82),
          ('Mike Cloud', 'RB', 84),
          ('Bill Romanowski', 'LB', 88)]),
 '113': ('mass', 'UMass', [('Mardy Gilyard', 'WR', 84), ('Victor Cruz', 'WR', 86)]),
 '12': ('ariz',
        'Arizona',
        [('Willie Tuitama', 'QB', 78),
         ('Nick Foles', 'QB', 88),
         ('Khalil Tate', 'QB', 84),
         ("Ka'Deem Carey", 'RB', 90),
         ('Mike Bell', 'RB', 84),
         ('Rob Gronkowski', 'TE', 95),
         ('Tedy Bruschi', 'LB', 92),
         ('Antoine Cason', 'DB', 86),
         ('Darry Beckwith', 'LB', 74)]),
 '150': ('duke',
         'Duke',
         [('Daniel Jones', 'QB', 86),
          ('Thaddeus Lewis', 'QB', 80),
          ('Clarkston Hines', 'WR', 84),
          ('Conner Vernon', 'WR', 84),
          ('Jamison Crowder', 'WR', 86)]),
 '151': ('ecu',
         'East Carolina',
         [('Jeff Blake', 'QB', 86),
          ('David Garrard', 'QB', 84),
          ('Chris Johnson', 'RB', 92),
          ('Dwayne Harris', 'WR', 84)]),
 '152': ('ncsu',
         'NC State',
         [('Philip Rivers', 'QB', 94),
          ('Russell Wilson', 'QB', 92),
          ('Ted Brown', 'RB', 90),
          ('Torry Holt', 'WR', 94),
          ('Koren Robinson', 'WR', 86),
          ('Mario Williams', 'DL', 94),
          ('Manny Lawson', 'LB', 86),
          ('Jim Ritcher', 'OL', 88)]),
 '153': ('unc',
         'North Carolina',
         [('Mitch Trubisky', 'QB', 86),
          ('Sam Howell', 'QB', 86),
          ('Kelvin Bryant', 'RB', 88),
          ('Giovani Bernard', 'RB', 88),
          ('Charlie Justice', 'RB', 92),
          ('Hakeem Nicks', 'WR', 88),
          ('Julius Peppers', 'DL', 96),
          ('Harris Barton', 'OL', 88),
          ('Dre Bly', 'DB', 88),
          ('Bruce Carter', 'LB', 84)]),
 '154': ('wake',
         'Wake Forest',
         [('Riley Skinner', 'QB', 80),
          ('Sam Hartman', 'QB', 84),
          ('Chris Barclay', 'RB', 82),
          ('Josh Adams', 'RB', 84),
          ('Desmond Clark', 'TE', 82),
          ('Michael Campanaro', 'WR', 82)]),
 '16': ('sac', 'Sacramento St', [('Jordan Devey', 'OL', 76), ('DeAndre Carter', 'WR', 80)]),
 '166': ('nmsu', 'New Mexico St', [('Tony Plummer', 'DB', 72), ('Larry Rose', 'RB', 78)]),
 '167': ('unm', 'New Mexico', [('Donovan Arnette', 'WR', 72), ('Rodney Ferguson', 'RB', 80)]),
 '183': ('syr',
         'Syracuse',
         [('Donovan McNabb', 'QB', 92),
          ('Marvin Harrison', 'WR', 95),
          ('Jim Brown', 'RB', 99),
          ('Larry Csonka', 'RB', 94),
          ('Floyd Little', 'RB', 93),
          ('Art Monk', 'WR', 94),
          ('Dwight Freeney', 'DL', 95),
          ('Tim Green', 'LB', 88),
          ('Jim Ringo', 'OL', 90)]),
 '189': ('bgsu', 'Bowling Green', [('Omar Jacobs', 'QB', 82), ('Kaleb Emsley', 'WR', 72), ('Matt Groff', 'K', 74)]),
 '193': ('moh', 'Miami OH', [('Ben Roethlisberger', 'QB', 96), ('Zac Dysert', 'QB', 78), ('Travis Brigham', 'LB', 72)]),
 '195': ('ohio', 'Ohio', [('Tyler Tettleton', 'QB', 80), ('Kalvin McRae', 'RB', 82), ('Donte Harden', 'RB', 76)]),
 '197': ('okst',
         'Oklahoma State',
         [('Barry Sanders', 'RB', 99),
          ('Thurman Thomas', 'RB', 95),
          ('Dez Bryant', 'WR', 94),
          ('Justin Blackmon', 'WR', 92),
          ('Rashaun Woods', 'WR', 88),
          ('Brandon Weeden', 'QB', 84),
          ('Mason Rudolph', 'QB', 84),
          ("Leslie O'Neal", 'DL', 92),
          ('Charlie Johnson', 'OL', 84),
          ('Russell Okung', 'OL', 88)]),
 '2005': ('afa',
          'Air Force',
          [('Beau Morgan', 'QB', 80),
           ('Chance Casey', 'DB', 74),
           ('Chad Hennings', 'DL', 88),
           ('Ernie Jennings', 'WR', 82)]),
 '2006': ('akr', 'Akron', [('Charlie Frye', 'QB', 82), ('Jabari Arthur', 'WR', 76)]),
 '202': ('tlsa', 'Tulsa', [('Paul Smith', 'QB', 80), ('Garrett Mills', 'TE', 80), ('Kevin Fitzpatrick', 'K', 74)]),
 '2026': ('app', 'App State', [('Armanti Edwards', 'QB', 88), ('Marcus Cox', 'RB', 84), ('Darrynton Evans', 'RB', 84)]),
 '2032': ('arst', 'Arkansas St', [('Ryan Aplin', 'QB', 80), ('Fredi Knighten', 'QB', 78), ('Reggie Mitch', 'RB', 74)]),
 '204': ('orst',
         'Oregon State',
         [('Derek Anderson', 'QB', 86),
          ('Sean Mannion', 'QB', 82),
          ('Jacquizz Rodgers', 'RB', 86),
          ('Steven Jackson', 'RB', 92),
          ('Brandon Browner', 'DB', 86),
          ('Chad Johnson', 'WR', 90),
          ('Mike Hass', 'WR', 86)]),
 '2050': ('ball', 'Ball State', [('Nate Davis', 'QB', 82), ('Dante Love', 'WR', 80), ('Blake Martin', 'RB', 74)]),
 '2084': ('buff', 'Buffalo', [('James Starks', 'RB', 84), ('Naaman Roosevelt', 'WR', 80), ('Khalil Mack', 'LB', 96)]),
 '21': ('sdsu',
        'San Diego State',
        [('Marshall Faulk', 'RB', 98),
         ('Rashaad Penny', 'RB', 90),
         ('Donnel Pumphrey', 'RB', 88),
         ('Brian Sipe', 'QB', 86),
         ('Haven Moses', 'WR', 84),
         ('Kawika Mitchell', 'LB', 82)]),
 '2116': ('ucf',
          'UCF',
          [('Daunte Culpepper', 'QB', 94),
           ('Blake Bortles', 'QB', 86),
           ('McKenzie Milton', 'QB', 86),
           ('Kevin Smith', 'RB', 90),
           ('Latavius Murray', 'RB', 84),
           ('Brandon Marshall', 'WR', 90),
           ('Shaquill Griffin', 'DB', 86),
           ('Shaquem Griffin', 'LB', 86)]),
 '2117': ('cmu', 'C Michigan', [('Dan LeFevour', 'QB', 86), ('Antonio Brown', 'WR', 94), ('Eric Thomas', 'WR', 76)]),
 '2132': ('cin',
          'Cincinnati',
          [('Gino Guidugli', 'QB', 80),
           ('Desmond Ridder', 'QB', 86),
           ('Gunner Kiel', 'QB', 78),
           ('Isaiah Pead', 'RB', 84),
           ('Travis Kelce', 'TE', 94),
           ('Brent Celek', 'TE', 84),
           ('Jason Kelce', 'OL', 90),
           ('Mike Mickens', 'DB', 82)]),
 '218': ('tem', 'Temple', [('Muhammad Wilkerson', 'DL', 90), ('Rod Streater', 'WR', 80), ('Paul Palmer', 'RB', 88)]),
 '2199': ('emu', 'E Michigan', [('Andy Schmitt', 'QB', 76), ('Tyler Jones', 'RB', 74)]),
 '221': ('pitt',
         'Pitt',
         [('Dan Marino', 'QB', 97),
          ('Tony Dorsett', 'RB', 98),
          ('Larry Fitzgerald', 'WR', 95),
          ('Darrelle Revis', 'DB', 96),
          ('Aaron Donald', 'DL', 99),
          ('Hugh Green', 'LB', 94),
          ('Bill Fralic', 'OL', 92),
          ('LeSean McCoy', 'RB', 92),
          ('Troy Polamalu', 'DB', 96),
          ('Mike Ditka', 'TE', 94),
          ('Antonio Bryant', 'WR', 86)]),
 '2226': ('fau', 'FAU', [('Lane Trainor', 'QB', 72), ('Devin Singletary', 'RB', 88), ('Harrison Bryant', 'TE', 84)]),
 '2229': ('fiu', 'FIU', [('T.Y. Hilton', 'WR', 90), ('Mario Pender', 'RB', 76)]),
 '2247': ('gast', 'Georgia St', [('Glenn Smith', 'WR', 72), ('Demarcus Kirk', 'RB', 74)]),
 '228': ('clem',
         'Clemson',
         [('Deshaun Watson', 'QB', 95),
          ('Trevor Lawrence', 'QB', 96),
          ('Tajh Boyd', 'QB', 88),
          ('C.J. Spiller', 'RB', 92),
          ('Travis Etienne', 'RB', 93),
          ('James Davis', 'RB', 86),
          ('Sammy Watkins', 'WR', 93),
          ('DeAndre Hopkins', 'WR', 95),
          ('Tee Higgins', 'WR', 90),
          ('Justyn Ross', 'WR', 86),
          ('Mike Williams', 'WR', 88),
          ('Gaines Adams', 'DL', 88),
          ('Clelin Ferrell', 'DL', 88),
          ('Dexter Lawrence', 'DL', 92),
          ('Christian Wilkins', 'DL', 90),
          ('Vic Beasley', 'LB', 88),
          ('Isaiah Simmons', 'LB', 90),
          ('Brian Dawkins', 'DB', 94),
          ('Homer Jordan', 'QB', 82),
          ('Steve Fuller', 'QB', 84)]),
 '23': ('sjsu', 'San José St', [('Jeff Garcia', 'QB', 90), ('Neil Parry', 'RB', 74), ('James Jones', 'WR', 86)]),
 '2305': ('ku',
          'Kansas',
          [('John Hadl', 'QB', 88),
           ('Todd Reesing', 'QB', 82),
           ('Gale Sayers', 'RB', 98),
           ('John Riggins', 'RB', 94),
           ('Tony Sands', 'RB', 82),
           ('Nolan Cromwell', 'DB', 88),
           ('Dana Stubblefield', 'DL', 90)]),
 '2306': ('ksu',
          'Kansas State',
          [('Collin Klein', 'QB', 88),
           ('Michael Bishop', 'QB', 90),
           ('Darren Sproles', 'RB', 92),
           ('Jordy Nelson', 'WR', 92),
           ('Quincy Morgan', 'WR', 84),
           ('Terrell Thomas', 'DB', 82),
           ('Damon Bolet', 'LB', 74),
           ('Martin Gramatica', 'K', 84)]),
 '2309': ('kent', 'Kent State', [('Julian Edelman', 'WR', 90), ('Joshua Cribbs', 'QB', 86)]),
 '2335': ('lib', 'Liberty', [('Malik Willis', 'QB', 86), ('Jessie Britt', 'WR', 74)]),
 '2348': ('lt',
          'Louisiana Tech',
          [('Terry Bradshaw', 'QB', 96), ('Luke McCown', 'QB', 80), ('Matt Mulligan', 'TE', 78)]),
 '235': ('mem',
         'Memphis',
         [('DeAngelo Williams', 'RB', 92),
          ('Joe Dorceus', 'DL', 74),
          ('Paxton Lynch', 'QB', 84),
          ('Brady White', 'QB', 78),
          ('Anthony Miller', 'WR', 88),
          ('Tony Pollard', 'RB', 88),
          ('Dontari Poe', 'DL', 90),
          ('Jacob Karam', 'QB', 76)]),
 '239': ('bay',
         'Baylor',
         [('Robert Griffin III', 'QB', 94),
          ('Bryce Petty', 'QB', 84),
          ('Nick Florence', 'QB', 80),
          ('Terrance Williams', 'WR', 88),
          ('Kendall Wright', 'WR', 88),
          ('Josh Gordon', 'WR', 90),
          ('Jaylon Smith', 'LB', 88),
          ('Mike Singletary', 'LB', 96)]),
 '2390': ('mia',
          'Miami',
          [('Bernie Kosar', 'QB', 90),
           ('Vinny Testaverde', 'QB', 90),
           ('Ken Dorsey', 'QB', 88),
           ('Gino Torretta', 'QB', 90),
           ('Jim Kelly', 'QB', 93),
           ('Clinton Portis', 'RB', 92),
           ('Edgerrin James', 'RB', 94),
           ('Willis McGahee', 'RB', 90),
           ('Ottis Anderson', 'RB', 88),
           ('Michael Irvin', 'WR', 95),
           ('Andre Johnson', 'WR', 94),
           ('Santana Moss', 'WR', 90),
           ('Reggie Wayne', 'WR', 92),
           ('Warren Sapp', 'DL', 96),
           ('Jerome Brown', 'DL', 92),
           ('Vince Wilfork', 'DL', 90),
           ('Ray Lewis', 'LB', 98),
           ('Jonathan Vilma', 'LB', 90),
           ('Dan Morgan', 'LB', 88),
           ('Ed Reed', 'DB', 97),
           ('Sean Taylor', 'DB', 96),
           ('Antrel Rolle', 'DB', 86),
           ('Jimmy Graham', 'TE', 88),
           ('Kellen Winslow II', 'TE', 90)]),
 '2393': ('mtsu', 'MTSU', [('Dwight Dasher', 'QB', 78), ('Phillip Tanner', 'RB', 80)]),
 '24': ('stan',
        'Stanford',
        [('Andrew Luck', 'QB', 97),
         ('John Elway', 'QB', 96),
         ('Jim Plunkett', 'QB', 92),
         ('Toby Gerhart', 'RB', 90),
         ('Christian McCaffrey', 'RB', 95),
         ('Bryce Love', 'RB', 90),
         ('Richard Sherman', 'DB', 92),
         ('Ed McCaffrey', 'WR', 86),
         ('David DeCastro', 'OL', 92),
         ('Zach Ertz', 'TE', 90)]),
 '242': ('rice', 'Rice', [('Tommy Kramer', 'QB', 86), ('James Casey', 'TE', 82), ('Trevor Cobb', 'RB', 84)]),
 '2426': ('navy',
          'Navy',
          [('Keenan Reynolds', 'QB', 88),
           ('Malcolm Perry', 'QB', 84),
           ('Chris McCoy', 'QB', 80),
           ('Joe Bellino', 'RB', 90),
           ('Napoleon McCallum', 'RB', 88),
           ('Roger Staubach', 'QB', 96)]),
 '2429': ('clt', 'Charlotte', [('Chris Reynolds', 'QB', 76), ('Benny LeMay', 'RB', 80)]),
 '2433': ('ulm', 'UL Monroe', [('Stan Humphries', 'QB', 86), ('Josh Bright', 'RB', 74)]),
 '2439': ('unlv',
          'UNLV',
          [('Randall Cunningham', 'QB', 94), ('Ickey Woods', 'RB', 86), ('Keenan McCardell', 'WR', 88)]),
 '2440': ('nev',
          'Nevada',
          [('Colin Kaepernick', 'QB', 92),
           ('Chris Ault', 'QB', 70),
           ('Vai Taua', 'RB', 84),
           ('Rishard Matthews', 'WR', 84)]),
 '2449': ('ndsu', 'N Dakota St', [('Carson Wentz', 'QB', 92), ('Easton Stick', 'QB', 84), ('Kyle Lauletta', 'QB', 70)]),
 '2459': ('niu', 'N Illinois', [('Jordan Lynch', 'QB', 88), ('Chad Spann', 'RB', 82), ('Tommylee Lewis', 'WR', 80)]),
 '248': ('hou',
         'Houston',
         [('Andre Ware', 'QB', 92),
          ('Case Keenum', 'QB', 88),
          ('Kevin Kolb', 'QB', 82),
          ('Jackie Battle', 'RB', 78),
          ('Vincent Marshall', 'WR', 78),
          ('Patrick Carr', 'RB', 74),
          ('Wilson Whitley', 'DL', 86),
          ('Jason Phillips', 'LB', 80)]),
 '249': ('unt',
         'North Texas',
         [('Patrick Cobbs', 'RB', 80),
          ('Lance Dunbar', 'RB', 82),
          ('Mason Fine', 'QB', 80),
          ('Jamal Hughley', 'WR', 74)]),
 '25': ('cal',
        'California',
        [('Aaron Rodgers', 'QB', 96),
         ('Jared Goff', 'QB', 92),
         ('Marshawn Lynch', 'RB', 94),
         ('Jahvid Best', 'RB', 88),
         ('DeSean Jackson', 'WR', 92),
         ('Keenan Allen', 'WR', 90),
         ('Ron Rivera', 'LB', 86),
         ('Nnamdi Asomugha', 'DB', 88),
         ('Chuck Muncie', 'RB', 90)]),
 '252': ('byu',
         'BYU',
         [('Steve Young', 'QB', 96),
          ('Jim McMahon', 'QB', 92),
          ('Ty Detmer', 'QB', 93),
          ('Robbie Bosco', 'QB', 86),
          ('Zach Wilson', 'QB', 88),
          ('Luke Staley', 'RB', 88),
          ('Jamaal Williams', 'RB', 84),
          ('Austin Collie', 'WR', 86),
          ('Marc Wilson', 'QB', 86),
          ('Kyle Van Noy', 'LB', 88)]),
 '2534': ('shsu', 'Sam Houston', [('Jeremiah Briscoe', 'QB', 80), ('Yedidiah Louis', 'WR', 76)]),
 '254': ('utah',
         'Utah',
         [('Alex Smith', 'QB', 90),
          ('Travis Wilson', 'QB', 78),
          ('John White', 'RB', 84),
          ('Devontae Booker', 'RB', 86),
          ('Carl Monroe', 'WR', 74),
          ('Eric Weddle', 'DB', 92),
          ('Star Lotulelei', 'DL', 88),
          ('Glover Quin', 'DB', 84)]),
 '256': ('jmu', 'James Madison', [('Vad Lee', 'QB', 78), ('Khalid Abdullah', 'RB', 80)]),
 '2567': ('smu',
          'SMU',
          [('Eric Dickerson', 'RB', 97),
           ('Craig James', 'RB', 88),
           ('Don Meredith', 'QB', 90),
           ('Emmanuel Sanders', 'WR', 88),
           ('Courtland Sutton', 'WR', 90),
           ('Jerry LeVias', 'WR', 88)]),
 '2572': ('usm',
          'Southern Miss',
          [('Brett Favre', 'QB', 97), ("De'Mond Parker", 'RB', 82), ('Sherrod Gideon', 'WR', 80)]),
 '258': ('uva',
         'Virginia',
         [('Matt Schaub', 'QB', 86),
          ('Aaron Brooks', 'QB', 82),
          ('Tiki Barber', 'RB', 90),
          ('Thomas Jones', 'RB', 88),
          ('Heath Miller', 'TE', 90),
          ('Chris Long', 'DL', 90),
          ('Patrick Kerney', 'DL', 86),
          ('Ronde Barber', 'DB', 90)]),
 '259': ('vt',
         'Virginia Tech',
         [('Michael Vick', 'QB', 96),
          ('Tyrod Taylor', 'QB', 86),
          ('Lee Suggs', 'RB', 86),
          ('Kevin Jones', 'RB', 88),
          ('Antonio Freeman', 'WR', 88),
          ('Isaiah Ford', 'WR', 84),
          ('Bruce Smith', 'DL', 98),
          ('Corey Moore', 'LB', 88),
          ('DeAngelo Hall', 'DB', 90),
          ('Kam Chancellor', 'DB', 92)]),
 '2623': ('most', 'Missouri St', [('Cody Wrangham', 'QB', 70), ('Dylan Cole', 'LB', 80)]),
 '2628': ('tcu',
          'TCU',
          [('Andy Dalton', 'QB', 88),
           ('Trevone Boykin', 'QB', 84),
           ('LaDainian Tomlinson', 'RB', 97),
           ('Matt Bryant', 'K', 82),
           ('Jerry Hughes', 'DL', 88),
           ('Jason Verrett', 'DB', 88),
           ('Josh Doctson', 'WR', 86),
           ('Jeremy Kerley', 'WR', 82)]),
 '2636': ('utsa', 'UTSA', [('Frank Harris', 'QB', 80), ('Sincere McCormick', 'RB', 84)]),
 '2638': ('utep', 'UTEP', [('Jordan Palmer', 'QB', 78), ('Johnnie Lee Higgins', 'WR', 82)]),
 '2641': ('ttu',
          'Texas Tech',
          [('Patrick Mahomes', 'QB', 98),
           ('Graham Harrell', 'QB', 86),
           ('Kliff Kingsbury', 'QB', 84),
           ('Wes Welker', 'WR', 90),
           ('Michael Crabtree', 'WR', 92),
           ('Danny Amendola', 'WR', 86),
           ('Byron Hanspard', 'RB', 88),
           ('Bam Morris', 'RB', 84),
           ('Zach Thomas', 'LB', 94),
           ('Gabe Rivera', 'DL', 90)]),
 '2649': ('tol', 'Toledo', [('Bruce Gradkowski', 'QB', 84), ('Chester Taylor', 'RB', 88), ('Kareem Hunt', 'RB', 90)]),
 '265': ('wsu',
         'Washington State',
         [('Drew Bledsoe', 'QB', 94),
          ('Ryan Leaf', 'QB', 86),
          ('Gardner Minshew', 'QB', 86),
          ('Rueben Mayes', 'RB', 90),
          ('Jason Gesser', 'QB', 80),
          ('Devard Darling', 'WR', 80)]),
 '2653': ('troy', 'Troy', [('Deonche Cool', 'QB', 70), ('Leopold Falck', 'K', 70), ('Shawn Clark', 'OL', 72)]),
 '2655': ('tuln',
          'Tulane',
          [('Shaun King', 'QB', 84),
           ('Matt Forte', 'RB', 90),
           ('Mewelde Moore', 'RB', 84),
           ('Cairo Santos', 'K', 86),
           ('Daren Street', 'WR', 74),
           ('Parnell Dickinson', 'QB', 78)]),
 '2711': ('wmu', 'W Michigan', [('Tim Hiller', 'QB', 80), ('Corey Davis', 'WR', 92), ('Jamauri Bogan', 'RB', 78)]),
 '2751': ('wyo', 'Wyoming', [('Josh Allen', 'QB', 95), ('Brett Smith', 'QB', 80), ('Brian Hill', 'RB', 84)]),
 '276': ('mrsh',
         'Marshall',
         [('Chad Pennington', 'QB', 90), ('Byron Leftwich', 'QB', 88), ('Ahmad Bradshaw', 'RB', 86)]),
 '277': ('wvu',
         'West Virginia',
         [('Geno Smith', 'QB', 86),
          ('Major Harris', 'QB', 88),
          ('Pat White', 'QB', 90),
          ('Steve Slaton', 'RB', 90),
          ('Noel Devine', 'RB', 86),
          ('Tavon Austin', 'WR', 90),
          ('Kevin White', 'WR', 86),
          ('Canute Curtis', 'LB', 82),
          ('Darryl Talley', 'LB', 88),
          ('Mike Barber', 'TE', 80)]),
 '278': ('fres',
         'Fresno State',
         [('Derek Carr', 'QB', 92),
          ('David Carr', 'QB', 88),
          ('Davante Adams', 'WR', 95),
          ('Ryan Mathews', 'RB', 88),
          ('Bernard Berrian', 'WR', 84),
          ('Toby Bailey', 'WR', 74)]),
 '290': ('gaso',
         'GA Southern',
         [('Adrian Peterson', 'RB', 88), ('Jerick McKinnon', 'RB', 86), ('Shai Werts', 'QB', 78)]),
 '295': ('odu', 'Old Dominion', [('Taylor Heinicke', 'QB', 84), ('Zach Pascal', 'WR', 80)]),
 '309': ('ul',
         'Louisiana',
         [('Brian Mitchell', 'RB', 90), ('Orlando Thomas', 'DB', 86), ('Charles Tillman', 'DB', 90)]),
 '324': ('ccu', 'Coastal', [('Alex Parsons', 'OL', 74), ('Jacqez Hairston', 'RB', 76)]),
 '326': ('txst', 'Texas St', [('Bradlee Anae', 'DL', 84), ('Eric Soza', 'QB', 74)]),
 '328': ('usu', 'Utah State', [('Bobby Wagner', 'LB', 94), ('Kerwynn Williams', 'RB', 82), ('Donald Brown', 'WR', 74)]),
 '338': ('kenn', 'Kennesaw St', [('Chandler Burks', 'QB', 74), ('Darnell Holland', 'RB', 76)]),
 '349': ('army',
         'Army',
         [('Doc Blanchard', 'RB', 94),
          ('Glenn Davis', 'RB', 95),
          ('Pete Dawkins', 'RB', 90),
          ('Ahmad Bradshaw', 'RB', 78),
          ('Trent Steelman', 'QB', 78),
          ('Joe Leahy', 'K', 72)]),
 '36': ('csu', 'Colorado State', [('Kapri Bibbs', 'RB', 82), ('Rashard Higgins', 'WR', 86), ('Joey Porter', 'LB', 90)]),
 '38': ('colo',
        'Colorado',
        [('Kordell Stewart', 'QB', 88),
         ('Sefo Liufau', 'QB', 80),
         ('Rashaan Salaam', 'RB', 94),
         ('Eric Bieniemy', 'RB', 88),
         ('Phillip Lindsay', 'RB', 86),
         ('Michael Westbrook', 'WR', 88),
         ('Daniel Graham', 'TE', 86),
         ('Alfred Williams', 'LB', 90),
         ('Herb Orvis', 'DL', 84)]),
 '41': ('conn', 'UConn', [('Dan Orlovsky', 'QB', 82), ('Donald Brown', 'RB', 88), ('Marcus Smith', 'LB', 84)]),
 '48': ('del', 'Delaware', [('Joe Flacco', 'QB', 90), ('Rich Gannon', 'QB', 88)]),
 '5': ('uab', 'UAB', [('Joe Webb', 'QB', 82), ('Gharun Hester', 'WR', 74), ('Chris Brown', 'RB', 78)]),
 '52': ('fsu',
        'Florida State',
        [('Charlie Ward', 'QB', 95),
         ('Chris Weinke', 'QB', 90),
         ('Jameis Winston', 'QB', 94),
         ('Dalvin Cook', 'RB', 95),
         ('Warrick Dunn', 'RB', 94),
         ('Greg Jones', 'RB', 86),
         ('Devonta Freeman', 'RB', 88),
         ('Peter Warrick', 'WR', 93),
         ('Randy Moss', 'WR', 98),
         ('Anquan Boldin', 'WR', 90),
         ('Rashad Greene', 'WR', 86),
         ('Ron Sellers', 'WR', 90),
         ('Kellen Winslow', 'TE', 96),
         ('Peter Boulware', 'LB', 92),
         ('Derrick Brooks', 'LB', 96),
         ('Marvin Jones', 'LB', 90),
         ('Deion Sanders', 'DB', 99),
         ('Terrell Buckley', 'DB', 90),
         ('Xavier Rhodes', 'DB', 88),
         ('Jalen Ramsey', 'DB', 95),
         ('Sebastian Janikowski', 'K', 90)]),
 '55': ('jxst', 'Jax State', [('Rakeem Sims', 'RB', 74), ('Zerrick Cooper', 'QB', 74)]),
 '58': ('usf',
        'South Florida',
        [('Marlon Mack', 'RB', 86),
         ('Matt Grothe', 'QB', 82),
         ('B.J. Daniels', 'QB', 80),
         ('George Selvie', 'DL', 86),
         ('Jason Pierre-Paul', 'DL', 92)]),
 '59': ('gt',
        'Georgia Tech',
        [('Calvin Johnson', 'WR', 98),
         ('Joe Hamilton', 'QB', 88),
         ('Demaryius Thomas', 'WR', 92),
         ('Jonathan Dwyer', 'RB', 84),
         ('Derrick Morgan', 'DL', 88),
         ('Pat Swilling', 'LB', 90),
         ('Billy Shaw', 'OL', 90)]),
 '6': ('usa', 'South Alabama', [('Jeremy Adam', 'QB', 72), ('Xavier Johnson', 'WR', 76)]),
 '62': ('haw',
        "Hawai'i",
        [('Colt Brennan', 'QB', 90), ('Timmy Chang', 'QB', 86), ('June Jones', 'QB', 78), ('Chad Owens', 'WR', 86)]),
 '66': ('isu',
        'Iowa State',
        [('Brock Purdy', 'QB', 88),
         ('Sage Rosenfels', 'QB', 80),
         ('Steele Jantz', 'QB', 74),
         ('David Montgomery', 'RB', 88),
         ('Troy Davis', 'RB', 92),
         ('Allen Lazard', 'WR', 84),
         ('K.J. Nunn', 'WR', 74),
         ('David Sims', 'DB', 78)]),
 '68': ('bois',
        'Boise State',
        [('Kellen Moore', 'QB', 92),
         ('Jared Zabransky', 'QB', 82),
         ('Brett Rypien', 'QB', 80),
         ('Ian Johnson', 'RB', 86),
         ('Jeremy Avery', 'RB', 80),
         ('Tyler Smith', 'RB', 74),
         ('Matt Miller', 'WR', 82),
         ('Titus Young', 'WR', 86),
         ('Doug Martin', 'RB', 88),
         ('Ryan Clady', 'OL', 90),
         ('Shea McClellin', 'LB', 84),
         ('Quinton Jackson', 'RB', 74)]),
 '87': ('nd',
        'Notre Dame',
        [('Joe Montana', 'QB', 97),
         ('John Huarte', 'QB', 88),
         ('Brady Quinn', 'QB', 86),
         ('Jimmy Clausen', 'QB', 84),
         ('Ian Book', 'QB', 82),
         ('Sam Hartman', 'QB', 80),
         ('Paul Hornung', 'RB', 95),
         ('Ricky Watters', 'RB', 90),
         ('Autry Denson', 'RB', 84),
         ('Jeremiah Owusu-Koramoah', 'LB', 90),
         ("Manti Te'o", 'LB', 92),
         ('Jaylon Smith', 'LB', 90),
         ('Tim Brown', 'WR', 97),
         ('Raghib Ismail', 'WR', 94),
         ('Golden Tate', 'WR', 90),
         ('Will Fuller', 'WR', 88),
         ('Michael Floyd', 'WR', 88),
         ('Tyler Eifert', 'TE', 90),
         ('Kyle Rudolph', 'TE', 86),
         ('Leon Hart', 'TE', 92),
         ('Ross Browner', 'DL', 94),
         ('Justin Tuck', 'DL', 90),
         ('Aaron Taylor', 'OL', 90),
         ('Zack Martin', 'OL', 92),
         ('Harrison Smith', 'DB', 90),
         ('Todd Lyght', 'DB', 88),
         ('Dave Duerson', 'DB', 86),
         ('George Gipp', 'RB', 94),
         ('Johnny Lujack', 'QB', 92),
         ('Angelo Bertelli', 'QB', 90),
         ('Joe Theismann', 'QB', 90),
         ('Bob Crable', 'LB', 88),
         ('Chris Zorich', 'DL', 90),
         ('Alan Faneca', 'OL', 92)]),
 '9': ('asu',
       'Arizona State',
       [('Jake Plummer', 'QB', 90),
        ('Danny White', 'QB', 88),
        ('Pat Tillman', 'DB', 90),
        ('Terrell Suggs', 'LB', 94),
        ('Mike Haynes', 'DB', 94),
        ('John Henry Johnson', 'RB', 88),
        ('Darren Woodson', 'DB', 90),
        ('Paul Justin', 'QB', 78)]),
 '97': ('lou',
        'Louisville',
        [('Lamar Jackson', 'QB', 97),
         ('Teddy Bridgewater', 'QB', 90),
         ('Brian Brohm', 'QB', 84),
         ('Johnny Unitas', 'QB', 95),
         ('Michael Bush', 'RB', 86),
         ('Deion Branch', 'WR', 88),
         ('Elvis Dumervil', 'DL', 90)]),
 '98': ('wku',
        'Western KY',
        [('Brandon Doughty', 'QB', 82), ('Antonio Andrews', 'RB', 84), ('Willie Taggart', 'QB', 78)])}


for _tid, (_slug, _school, _players) in MORE_TEAMS.items():
    T(_tid, _slug, _school, _players)

def build():
    players = []
    teams_index = {}
    seen_ids = set()
    for tid, (slug, school, plist) in sorted(RAW.items(), key=lambda x: x[1][1].lower()):
        teams_index[tid] = {"id": tid, "slug": slug, "name": school, "count": 0}
        for name, pos, ovr in plist:
            ovr = int(max(40, min(99, ovr)))
            pid = make_id(slug, name)
            # Ensure unique ids across catalog
            base = pid
            n = 2
            while pid in seen_ids:
                pid = f"{base}-{n}"
                n += 1
            seen_ids.add(pid)
            players.append({
                "id": pid,
                "n": name,
                "p": pos,
                "schoolId": tid,
                "school": school,
                "ovr": ovr,
                "cost": cost_for_ovr(ovr),
            })
            teams_index[tid]["count"] += 1
    players.sort(key=lambda x: (-x["ovr"], x["school"], x["n"]))
    return {
        "version": 1,
        "generatedBy": "scripts/build_alltime_catalog.py",
        "notes": "Real historical CFB players only. OVR is video-game style (40-99). Cost scales with OVR.",
        "positions": ["QB","RB","WR","TE","OL","DL","LB","DB","K","P"],
        "costFormula": "round(8 + (ovr-39)^2 * 0.22)",
        "playerCount": len(players),
        "teamCount": len(teams_index),
        "teams": teams_index,
        "players": players,
    }

def main():
    data = build()
    outp = ROOT / "data" / "alltime-players.json"
    outp.write_text(json.dumps(data, separators=(",", ":")) + "\n")
    # Also pretty sample stats
    print(f"Wrote {outp}")
    print(f"Players: {data['playerCount']} across {data['teamCount']} teams")
    by_pos = {}
    for p in data["players"]:
        by_pos[p["p"]] = by_pos.get(p["p"], 0) + 1
    print("By position:", dict(sorted(by_pos.items())))
    # Sample prices
    for o in (50, 70, 85, 95, 99):
        print(f"  OVR {o} -> {cost_for_ovr(o)} coins")
    top = data["players"][:8]
    print("Top OVRs:", [(p["n"], p["school"], p["ovr"], p["cost"]) for p in top])

if __name__ == "__main__":
    main()
